Maets/Models/Dtos/Shared/EntityDto.cs
namespace Maets.Models.Dtos.Shared;

public abstract class EntityDto
{
    public Guid Id { get; set; }
}

Maets/Controllers/AboutController.cs
using Maets.Data;
using Maets.Domain.Seed;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Maets.Controllers;

public class AboutController : MaetsController
{
    private readonly MaetsDbContext _context;

    public AboutController(MaetsDbContext context)
    {
        _context = context;
    }
    
    public async Task<IActionResult> Index()
    {
        var maetsAppId = await _context.Apps
            .Where(x => x.Title == AppsSeedData.DefaultAppTitle)
            .Select(x => x.Id)
            .FirstAsync();
        return RedirectToPage("/store/app", new { id = maetsAppId });
    }

    public IActionResult Home()
    {
        return RedirectToPage("/store/home");
    }

    public IActionResult Privacy()
    {
        return View();
    }
}

Maets/Controllers/AppsController.cs
using AutoMapper;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Maets.Data;
using Maets.Domain.Constants;
using Maets.Domain.Entities;
using Maets.Extensions;
using Maets.Models.Dtos.Apps;
using Maets.Models.ExternalData;
using Maets.Services.Apps;
using Maets.Services.ExternalData;
using Maets.Services.Files;
using Maets.Services.Labels;
using Microsoft.AspNetCore.Authorization;

namespace Maets.Controllers;

[Authorize(Roles = RoleNames.AdminOrModerator)]
public class AppsController : MaetsController
{
    private readonly MaetsDbContext _context;
    private readonly IAppsService _appsService;
    private readonly IFileWriteService _fileWriteService;
    private readonly ILabelsService _labelsService;
    private readonly IMapper _mapper;
    private readonly ExcelDataService _excelDataService;
    private readonly DocxDataService _docxDataService;
    private readonly DataTransformationService _transformationService;

    public AppsController(MaetsDbContext context, IFileWriteService fileWriteService, ILabelsService labelsService, IMapper mapper, DataTransformationService transformationService, ExcelDataService excelDataService, IAppsService appsService, DocxDataService docxDataService)
    {
        _context = context;
        _fileWriteService = fileWriteService;
        _labelsService = labelsService;
        _mapper = mapper;
        _transformationService = transformationService;
        _excelDataService = excelDataService;
        _appsService = appsService;
        _docxDataService = docxDataService;
    }

    // GET: Apps
    public async Task<IActionResult> Index()
    {
        var apps = await _context.Apps
            .Include(a => a.Labels)
            .Include(a => a.Developers)
            .Include(a => a.Publisher)
            .ToListAsync();

        var appDtos = _mapper.Map<List<AppTableDto>>(apps);
        
        ViewData["SelectableApps"] = new SelectList(apps, "Id", "Title");
        
        return View(appDtos);
    }

    // GET: Apps/Details/5
    public async Task<IActionResult> Details(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var app = await _context.Apps
            .Include(a => a.Publisher)
            .FirstOrDefaultAsync(m => m.Id == id);
        
        if (app == null)
        {
            return NotFound();
        }

        return View(app);
    }

    // GET: Apps/Create
    public async Task<IActionResult> Create()
    {
        await LoadViewData();
        return View();
    }

    // POST: Apps/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(AppCreateDto appDto)
    {
        if (!ModelState.IsValid)
        {
            await LoadViewData();
            return View(appDto);
        }

        if (await _context.Apps.AnyAsync(x => x.Title == appDto.Title))
        {
            ModelState.AddModelError("title", "App with the same title already exists");
            await LoadViewData();
            return View(appDto);
        }

        await _appsService.CreateApp(appDto);
        
        return RedirectToAction(nameof(Index));
    }

    // GET: Apps/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var app = await _context.Apps
            .Include(x => x.Publisher)
            .Include(x => x.Developers)
            .Include(x => x.Labels)
            .FirstOrDefaultAsync(x => x.Id == id);
        
        if (app == null)
        {
            return NotFound();
        }

        var appDto = _mapper.Map<AppEditDto>(app);
        
        await LoadViewData();
        return View(appDto);
    }

    // POST: Apps/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, AppEditDto appDto)
    {
        if (!ModelState.IsValid)
        {
            await LoadViewData();
            return View(appDto);
        }
        
        var app = await _context.Apps
            .Include(x => x.Publisher)
            .Include(x => x.Developers)
            .Include(x => x.Labels)
            .Include(x => x.MainImage)
            .Include(x => x.Screenshots)
            .FirstOrDefaultAsync(x => x.Id == id);
        
        if (app is null)
        {
            return NotFound();
        }

        _mapper.Map(appDto, app);

        var publisher = await _context.Companies.FirstOrDefaultAsync(x => x.Id == appDto.PublisherId);
        if (publisher is not null)
        {
            app.Publisher = publisher;
        }

        var developers = await _context.Companies
            .Where(x => appDto.DeveloperIds.Contains(x.Id))
            .ToListAsync();
        app.Developers = developers;

        app.Labels = (await _labelsService.GetOrAddLabelsByNames(appDto.Labels)).ToList();

        if (appDto.MainImage is not null)
        {
            if (app.MainImage is not null)
            {
                await _fileWriteService.DeleteFileAsync(app.MainImage);
            }
            var mainImageKey = _appsService.BuildAppScreenshotKey(app.Id);
            app.MainImage = await _fileWriteService.UploadFileAsync(mainImageKey, appDto.MainImage.OpenReadStream());
        }

        if (appDto.Screenshots is not null)
        {
            foreach (var oldScreenshot in app.Screenshots)
            {
                await _fileWriteService.DeleteFileAsync(oldScreenshot);
            }
            app.Screenshots.Clear();
            foreach (var screenshot in appDto.Screenshots)
            {
                var fileKey = _appsService.BuildAppScreenshotKey(app.Id);
                var file = await _fileWriteService.UploadFileAsync(fileKey, screenshot.OpenReadStream());
                app.Screenshots.Add(file);
            }
        }

        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

    // GET: Apps/Delete/5
    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var app = await _context.Apps
            .Include(a => a.Publisher)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (app == null)
        {
            return NotFound();
        }

        return View(app);
    }

    // POST: Apps/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        var app = await _context.Apps.FindAsync(id);

        if (app is not null)
        {
            _context.Apps.Remove(app);
            await _context.SaveChangesAsync();    
        }
        
        return RedirectToAction(nameof(Index));
    }

    [HttpGet, ActionName("ExportSpreadsheet")]
    public async Task<IActionResult> ExportSpreadsheet(IEnumerable<Guid>? selectedAppIds = null)
    {
        var table = await GetExportTable(selectedAppIds);
        
        using var memoryStream = new MemoryStream();
        _excelDataService.ExportSpreadsheetToStream(memoryStream, table);
        await memoryStream.FlushAsync();
        
        return new FileContentResult(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        {
            FileDownloadName = $"AppsExport-{DateTime.Now}.xlsx"
        };
    }
    
    [HttpGet, ActionName("ExportDocument")]
    public async Task<IActionResult> ExportDocument(IEnumerable<Guid>? selectedAppIds = null)
    {
        var table = await GetExportTable(selectedAppIds);

        using var memoryStream = new MemoryStream();
        _docxDataService.ExportDocumentToStream(memoryStream, table);
        await memoryStream.FlushAsync();
        
        return new FileContentResult(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        {
            FileDownloadName = $"AppsExport-{DateTime.Now}.docx"
        };
    }

    [HttpPost, ActionName("ImportSpreadsheet")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ImportFromSpreadsheet(IFormFile spreadsheetFile)
    {
        if (!ModelState.IsValid)
        {
            return RedirectToAction(nameof(Index));
        }

        try
        {
            await using var fileStream = spreadsheetFile.OpenReadStream();
            var tableData = _excelDataService.ImportFromSpreadsheetStream(fileStream);
            var apps = _transformationService.FromTableData<AppExternalDto>(tableData);

            await AddImportedApps(apps);
        }
        catch (Exception)
        {
            ModelState.AddModelError("spreadsheetFile", "Invalid spreadsheet");
        }

        return RedirectToAction(nameof(Index));
    }
    
    [HttpPost, ActionName("ImportDocument")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ImportFromDocument(IFormFile documentFile)
    {
        if (!ModelState.IsValid)
        {
            return RedirectToAction(nameof(Index));
        }

        try
        {
            await using var fileStream = documentFile.OpenReadStream();
            var tableData = _docxDataService.ImportFromDocumentStream(fileStream);
            var apps = _transformationService.FromTableData<AppExternalDto>(tableData);

            await AddImportedApps(apps);
        }
        catch (Exception)
        {
            ModelState.AddModelError("documentFile", "Invalid spreadsheet");
        }

        return RedirectToAction(nameof(Index));
    }


Maets/Controllers/ReviewsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Maets.Data;
using Maets.Domain.Constants;
using Maets.Domain.Entities;
using Maets.Extensions;
using Maets.Models.Dtos.Reviews;
using Maets.Models.Exceptions;
using Microsoft.AspNetCore.Authorization;

namespace Maets.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly MaetsDbContext _context;
        private readonly IMapper _mapper;

        public ReviewsController(MaetsDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var reviews = await _context.Reviews
                .Include(r => r.App)
                .Include(r => r.Author)
                .OrderByDescending(r => r.CreationDate)
                .ToListAsync();
            var dtos = _mapper.Map<List<ReviewReadDto>>(reviews);
            return View(dtos);
        }

        // GET: Reviews/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return RedirectToPage("/store/review", new { Id = id.Value });
        }

        // GET: Reviews/Create
        [Authorize]
        public async Task<IActionResult> Create(Guid id)
        {
            if (!await _context.Apps.AnyAsync(x => x.Id == id))
            {
                throw new NotFoundException<App>();
            }
            
            if (await _context.Reviews.AnyAsync(x => x.AppId == id && x.AuthorId == User.GetId()))
            {
                return View("AlreadyReviewed");
            }
            
            return View(new ReviewWriteDto
            {
                AppId = id
            });
        }

        // POST: Reviews/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Guid id, ReviewWriteDto reviewDto)
        {
            if (!ModelState.IsValid || id != reviewDto.AppId)
            {
                return View(reviewDto);
            }
            
            if (!await _context.Apps.AnyAsync(x => x.Id == id))
            {
                throw new NotFoundException<App>();
            }

            if (await _context.Reviews.AnyAsync(x => x.AppId == id && x.AuthorId == User.GetId()))
            {
                return View("AlreadyReviewed");
            }

            var review = new Review
            {
                Id = Guid.NewGuid(),
                Title = reviewDto.Title,
                Description = reviewDto.Description,
                Score = reviewDto.Score,
                AppId = reviewDto.AppId,
                AuthorId = User.GetId()
            };
            
            _context.Add(review);
            await _context.SaveChangesAsync();
            
            return RedirectToPage("/store/app", new { Id = id });
        }

        // GET: Reviews/Edit/5
        [Authorize(Roles = RoleNames.AdminOrModerator)]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .Include(x => x.App)
                .Include(x => x.Author)
                .FirstOrDefaultAsync(x => x.Id == id.Value);

            if (review is null)
            {
                throw new NotFoundException<Review>();
            }
            
            return View(_mapper.Map<ReviewWriteDto>(review));
        }

        // POST: Reviews/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleNames.AdminOrModerator)]
        public async Task<IActionResult> Edit(Guid id, ReviewWriteDto reviewDto)
        {
            if (!ModelState.IsValid)
            {
                return View(reviewDto);
            }
            
            var review = await _context.Reviews
                .Include(x => x.App)
                .Include(x => x.Author)
                .FirstOrDefaultAsync(x => x.Id == id);

            if (review is null)
            {
                throw new NotFoundException<Review>();
            }

            _mapper.Map(reviewDto, review);
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleNames.AdminOrModerator)]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var review = await _context.Reviews.FindAsync(id);
            if (review is not null)
            {
                _context.Reviews.Remove(review);
                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Maets/Views/Shared/_BackToIndexPartial.cshtml
<a asp-action="Index" class="btn btn-outline-primary">
    <i class="fas fa-backward"></i> Back to List
</a>

Maets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Maets - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/vendor.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Maets.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand position-md-absolute" style="left: 1rem; font-size: 1.5rem" asp-page="/store/home">
                <i class="fas fa-cubes"></i> Maets
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbar-collapse">
                <partial name="_NavMenuPartial"/>
                <div class="position-md-absolute" style="right: 1rem">
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="pb-3">
    <div class="container">
       @RenderBody() 
    </div>
</main>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - <a asp-area="" asp-controller="About" asp-action="Index">Maets</a> - <a asp-area="" asp-controller="About" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/js/vendor.min.js"></script>
<script src="~/js/dataTables.bootstrap5.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Maets/Views/Shared/_NavMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Maets.Extensions
@using Maets.Domain.Entities.Identity
@inject SignInManager<ApplicationUser> SignInManager
<ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-grow-1 justify-content-center">
    <li class="nav-item dropdown">
        <a class="nav-link"
           asp-area="" asp-page="/store/home">
            <i class="fas fa-shopping-cart"></i> Store
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" asp-page="/store/home">Home</a></li>
            <li><a class="dropdown-item" asp-page="/store/search">Search</a></li>
        </ul>
    </li>
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" asp-page="/collection/index">
                <i class="fas fa-bars-staggered"></i> Collection
            </a>
        </li>
    }
    @if (SignInManager.IsAdminOrModerator(User))
    {
        <li class="nav-item">
            <a class="nav-link" asp-page="/stats/index">
                <i class="fa-solid fa-table"></i> Stats
            </a>
        </li>
    }
    @if (SignInManager.IsAdminOrModerator(User))
    {
        <li class="nav-item dropdown">
            <a class="nav-link" asp-area="" asp-controller="Apps" asp-action="Index">
                <i class="fas fa-screwdriver-wrench"></i> Administration
            </a>
            <ul class="dropdown-menu">
                @if (SignInManager.IsAdmin(User))
                {
                    <li><a class="dropdown-item" asp-controller="Users" asp-action="Index">Users</a></li>
                    <li><a class="dropdown-item" asp-controller="Companies" asp-action="Index">Companies</a></li>
                }
                <li><a class="dropdown-item" asp-controller="Reviews" asp-action="Index">Reviews</a></li>
                <li><a class="dropdown-item" asp-controller="Apps" asp-action="Index">Apps</a></li>
            </ul>
        </li>
    }
    <li class="nav-item dropdown">
        <a class="nav-link">
            <i class="fas fa-search"></i> Advanced Search
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter1">Filter1</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter2">Filter2</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter3">Filter3</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter4">Filter4</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter5">Filter5</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter6">Filter6</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter7">Filter7</a></li>
            <li><a class="dropdown-item" asp-controller="AdvancedSearch" asp-action="Filter8">Filter8</a></li>
        </ul>
    </li>
</ul>

Maets/Views/Shared/_TableFileActionsPartial.cshtml
@model Maets.Models.ViewModels.TableActionsViewModel

<div class="accordion my-2" id="tableActionsAccordion">
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button btn-outline-secondary collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                Import
            </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#tableActionsAccordion">
            <form enctype="multipart/form-data" method="post" asp-action="ImportSpreadsheet" class="form-group d-flex mx-1 my-2">
                <input id="importXlsxButton" type="submit" value="Import from .xlsx" disabled class="btn btn-sm btn-outline-primary w-25"/>
                <input id="importXlsxInput" name="spreadsheetFile" type="file" class="form-control"/>
            </form>
            <form enctype="multipart/form-data" method="post" asp-action="ImportDocument" class="form-group d-flex mx-1 my-2">
                <input id="importDocxButton" type="submit" value="Import from .docx" disabled class="btn btn-sm btn-outline-primary w-25"/>
                <input id="importDocxInput" name="documentFile" type="file" class="form-control"/>
            </form>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
            <button class="accordion-button btn-outline-secondary collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                Export
            </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#tableActionsAccordion">
            <form method="get" asp-action="ExportSpreadsheet" class="form-group mx-1 my-2">
                <a asp-controller="Apps" asp-action="ExportSpreadsheet" class="btn btn-outline-primary mx-1 my-2">
                    Export All as .xlsx
                </a>
                <input id="exportXlsxButton" type="submit" value="Export Selected as .xlsx" disabled class="btn btn-outline-primary"/>
                <select id="exportXlsxSelect" name="selectedAppIds" multiple class="form-control search-select" asp-items="@ViewContext.ViewBag.SelectableApps"></select>
            </form>
            <form method="get" asp-action="ExportDocument" class="form-group mx-1 my-2">
                <a asp-controller="Apps" asp-action="ExportDocument" class="btn btn-outline-primary mx-1 my-2">
                    Export All as .docx
                </a>
                <input id="exportDocxButton" type="submit" value="Export Selected as .docx" disabled class="btn btn-outline-primary"/>
                <select id="exportDocxSelect" name="selectedAppIds" multiple class="form-control search-select" asp-items="@ViewContext.ViewBag.SelectableApps"></select>
            </form>
        </div>
    </div>
</div>

Maets/Views/Shared/_TablePartial.cshtml
@using Maets.Helpers
@using Maets.Extensions
@model Maets.Models.ViewModels.TableViewModel

@{
    var items = Model.GetItems().ToArray();
    var columns = Model.GetColumns().ToArray();
}
<div class="table-responsive">
<table class="table table-net">
    <thead>
    <tr>
        @foreach (var column in columns)
        {
            <th>@column.Header</th>
        }
        @if (Model.HasActions)
        {
            <th/>
        }
    </tr>
    </thead>
    <tbody>
    @foreach (var item in items)
    {
        <tr>
            @foreach (var column in columns)
            {
                <td>
                    @column.GetDisplay(item)
                </td>
            }
            @if (Model.HasActions)
            {
                <td>
                    <div class="d-flex flex-nowrap flex-row" style="gap: 6px">
                        @if (Model.CanViewDetails)
                        {
                            <a class="btn btn-sm btn-info flex-grow-1" asp-action="Details" asp-route-id="@Model.GetItemId(item)">
                                <i class="fas fa-asterisk"></i> Details
                            </a>
                        }
                        @if (Model.CanEdit)
                        {
                            <a class="btn btn-sm btn-primary flex-grow-1" asp-action="Edit" asp-route-id="@Model.GetItemId(item)">
                                <i class="fas fa-pen-to-square"></i> Edit
                            </a>
                        }
                        @if (Model.CanDelete)
                        {
                            <a class="btn btn-sm btn-danger flex-grow-1" asp-action="Delete" asp-route-id="@Model.GetItemId(item)">
                                <i class="fas fa-trash-can"></i> Delete
                            </a>
                        }
                    </div>
                </td>
            }
        </tr>
    }
    @if (Model.CanCreate)
    {
        <tr>
            @foreach (var _ in columns)
            {
                <td/>
            }
            <td>
                <a class="btn btn-sm btn-success w-100" asp-action="Create">
                    <i class="fas fa-plus"></i> Create New
                </a>
            </td>
        </tr>
    }

    </tbody>
</table>
</div>

Maets/Views/Shared/_TinyMcScriptsPartial.cshtml
<script src="/public/jquery/jquery.min.js"></script>
<script src="/public/tinymce/tinymce.min.js"></script>
<script src="/public/tinymce-jquery/tinymce-jquery.min.js"></script>
<script>
    $('textarea.html-editor').tinymce({
        skin: 'oxide-dark',
        max_height: 800,
        min_height: 100,
        min_width: 400,
        plugins: 'preview importcss searchreplace autolink directionality code visualblocks visualchars fullscreen link template codesample table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount help charmap quickbars emoticons',
        menubar: 'file edit view insert format tools table help',
        toolbar: 'undo redo | bold italic underline strikethrough | fontfamily fontsize blocks | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview print | template link anchor codesample | ltr rtl',
        toolbar_sticky: true,
        toolbar_mode: 'sliding',
        content_css: 'css/vendor.min.css'
    });
</script>